import { test, expect } from '@playwright/test'

for (const width of [390, 1280]) test(`existing customer autofill keeps new job fields at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  const owner = { id: 'owner', name: 'Owner', role: 'owner', email: 'owner@example.com' }
  const job = { id: 'old-job', customer: 'David Smith', phone: '3175550123', email: 'david@example.com', address: '123 Test Street', appliance: 'Old washer', issue: 'Old problem', service_date: '2026-09-01', service_window: '9:00 AM - 11:00 AM', status: 'complete', invoice: 100, paid: true, created_at: '2026-09-01T12:00:00Z', finance_items: [], payments: [], model_photo_attachments: [] }
  await page.addInitScript(user => localStorage.setItem('alex-crm-auth', JSON.stringify({ token: 'test-only', user })), owner)
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    if (url.port === '5186') return route.continue()
    return route.fulfill({ json: url.pathname === '/api/auth/me' ? owner : url.pathname === '/api/jobs' ? [job, { ...job, id: 'another-old-job' }] : url.pathname === '/api/jobs/old-job' ? job : url.pathname === '/api/jobs/another-old-job' ? { ...job, id: 'another-old-job' } : [] })
  })
  await page.goto('/')
  await page.locator('.schedule-floating-menu').click()
  await page.getByRole('button', { name: 'New job', exact: true }).click()
  const form = page.locator('#new-job')
  await form.getByLabel('Appliance', { exact: true }).fill('New dryer')
  await form.getByLabel('Problem', { exact: true }).fill('New problem')
  const date = await form.getByLabel('Date', { exact: true }).inputValue()
  const time = await form.getByRole('checkbox').evaluateAll(elements => elements.map(element => (element as HTMLInputElement).checked))
  await form.getByLabel('Customer', { exact: true }).fill('sMiTh')
  const results = page.getByRole('group', { name: 'Matching customers' })
  await expect(results.getByRole('button')).toHaveCount(1)
  await results.getByRole('button').click()
  await expect(form.getByLabel('Customer', { exact: true })).toHaveValue('David Smith')
  await expect(form.getByLabel('Phone', { exact: true })).toHaveValue(job.phone)
  await expect(form.getByLabel('Email', { exact: true })).toHaveValue(job.email)
  await expect(form.getByLabel('Address', { exact: true })).toHaveValue(job.address)
  await expect(form.getByLabel('Appliance', { exact: true })).toHaveValue('New dryer')
  await expect(form.locator('textarea')).toHaveValue('New problem')
  await expect(form.getByLabel('Date', { exact: true })).toHaveValue(date)
  expect(await form.getByRole('checkbox').evaluateAll(elements => elements.map(element => (element as HTMLInputElement).checked))).toEqual(time)
  await form.getByRole('checkbox', { name: '3:00 PM - 5:00 PM', exact: true }).check()
  await expect(form.getByRole('checkbox', { name: '9:00 AM - 11:00 AM', exact: true })).toBeChecked()
  await expect(form.getByRole('checkbox', { name: '3:00 PM - 5:00 PM', exact: true })).toBeChecked()
  await expect(results).toHaveCount(0)
  await page.screenshot({ path: `test-results/customer-search-${width}.png` })
  await page.getByRole('button', { name: 'Open menu', exact: true }).click()
  await page.getByRole('button', { name: 'Clients', exact: true }).click()
  await expect(page.getByLabel('Search clients', { exact: true })).toHaveCSS('height', '52px')
  await expect(page.getByLabel('Search clients', { exact: true })).toHaveCSS('border-radius', '8px')
  await expect(page.getByLabel('Search clients', { exact: true })).toHaveCSS('font-size', '13px')
  await expect(page.getByLabel('Search clients', { exact: true })).toHaveCSS('font-weight', '400')
  await page.screenshot({ path: `test-results/client-search-field-${width}.png` })
  await page.getByLabel('Search clients', { exact: true }).fill('smith')
  await expect(page.locator('.client-card')).toHaveCount(3)
  await expect(page.locator('.client-profile-card')).toHaveCount(1)
  const orderLabels = await page.locator('.client-order-number').allTextContents()
  expect(new Set(orderLabels).size).toBe(2)
  expect(orderLabels.every(label => label.startsWith('ORDER #'))).toBe(true)
  await expect(page.locator('.client-order-date').first()).toHaveText('09/01/26')
  const numberBox = await page.locator('.client-order-number').first().boundingBox()
  const dateBox = await page.locator('.client-order-date').first().boundingBox()
  expect(dateBox!.x).toBeGreaterThan(numberBox!.x + numberBox!.width)
  expect(Math.abs(dateBox!.y - numberBox!.y)).toBeLessThan(5)
  for (let index = 0; index < 2; index++) {
    const number = (await page.locator('.client-order-number').nth(index).textContent())!.replace('ORDER #', '')
    await page.locator('.client-order-card').nth(index).click()
    await expect(page.locator('.workiz-job-header')).toContainText(number)
    await expect(page.getByRole('heading', { name: 'Edit client', exact: true })).toHaveCount(0)
    await page.evaluate(() => window.dispatchEvent(new CustomEvent('alexNativeBackSwipe')))
    await expect(page.locator('.clients-page')).toBeVisible()
  }
  await page.locator('.client-profile-card').click()
  await expect(page.getByRole('heading', { name: 'Edit client', exact: true })).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('alexNativeBackSwipe')))
  await expect(page.locator('.clients-page')).toBeVisible()
  await page.getByLabel('Search clients', { exact: true }).fill('not a customer')
  await expect(page.getByText('No matching clients', { exact: true })).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('alexNativeBackSwipe')))
  await expect(page.locator('.clients-page')).toHaveCount(0)
})
