import { test, expect } from '@playwright/test'

for (const width of [320, 390, 1280]) test(`CRM clock picker and Time Off at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  const user = { id: 'owner', email: 'owner@example.com', name: 'Owner', role: 'owner' }
  let saved: { service_windows: string[]; all_day: boolean } | undefined
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.addInitScript(user => localStorage.setItem('alex-crm-auth', JSON.stringify({ token: 'test', user })), user)
  await page.route('**/*', async route => {
    const url = new URL(route.request().url())
    if (url.port === '5186') return route.continue()
    if (url.pathname === '/api/availability-blocks' && route.request().method() === 'POST') saved = route.request().postDataJSON()
    await route.fulfill({ json: url.pathname === '/api/auth/me' ? user : [] })
  })
  await page.goto('/')
  const quick = page.getByRole('button', { name: 'Quick actions', exact: true })
  await expect(quick).toBeVisible()
  await expect(page.locator('.quick-actions')).toHaveCSS('opacity', '0', { timeout: 8000 })
  await page.locator('body').dispatchEvent('pointerdown')
  await expect(page.locator('.quick-actions')).toHaveCSS('opacity', '1')
  await quick.click()
  const actions = page.getByRole('group', { name: 'Quick actions', exact: true })
  await expect(actions.getByRole('button')).toHaveCount(3)
  await page.screenshot({ path: `test-results/quick-actions-${width}.png` })
  await actions.getByRole('button', { name: 'Clients', exact: true }).click()
  await expect(quick).toHaveCount(0)
  await page.getByRole('button', { name: 'Open menu', exact: true }).click()
  await page.getByRole('button', { name: 'Jobs', exact: true }).click()
  await quick.click()
  await expect(actions).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(actions).toHaveCount(0)
  await page.getByRole('button', { name: 'Open menu', exact: true }).click()
  await page.getByRole('button', { name: 'Time off', exact: true }).click()
  await page.getByLabel('All day', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Add time', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Select time' })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Hour', { exact: true }).fill('10')
  await dialog.getByLabel('Minute', { exact: true }).fill('35')
  await dialog.getByRole('button', { name: 'AM', exact: true }).click()
  await dialog.screenshot({ path: `test-results/time-picker-${width}.png` })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'OK', exact: true }).click()
  await page.getByRole('button', { name: 'End time 1: 11:35 AM', exact: true }).click()
  await dialog.getByLabel('Hour', { exact: true }).fill('12')
  await dialog.getByLabel('Minute', { exact: true }).fill('05')
  await dialog.getByRole('button', { name: 'PM', exact: true }).click()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'End time 1: 11:35 AM', exact: true }).click()
  await dialog.getByLabel('Hour', { exact: true }).fill('12')
  await dialog.getByLabel('Minute', { exact: true }).fill('05')
  await dialog.getByRole('button', { name: 'PM', exact: true }).click()
  await dialog.getByRole('button', { name: 'OK', exact: true }).click()
  await page.locator('.time-off-modal').getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => saved).toEqual(expect.objectContaining({ service_windows: ['10:35 AM - 12:05 PM'], all_day: false }))
  await page.getByRole('button', { name: 'Open menu', exact: true }).click()
  await page.getByRole('button', { name: 'New job', exact: true }).click()
  await page.getByRole('button', { name: /^Start time 1:/ }).click()
  await dialog.getByRole('button', { name: 'hour 9', exact: true }).click()
  await dialog.getByRole('button', { name: 'minute 15', exact: true }).click()
  await dialog.getByRole('button', { name: 'OK', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start time 1: 9:15 AM', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Start time 1:/ }).click()
  await dialog.getByLabel('Hour', { exact: true }).fill('12')
  await dialog.getByLabel('Minute', { exact: true }).fill('00')
  await dialog.getByRole('button', { name: 'PM', exact: true }).click()
  await dialog.getByRole('button', { name: 'OK', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start time 1: 12:00 PM', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^End time 1:/ }).click()
  await dialog.getByLabel('Hour', { exact: true }).fill('1')
  await dialog.getByLabel('Minute', { exact: true }).fill('00')
  await dialog.getByRole('button', { name: 'OK', exact: true }).click()
  const form = page.locator('#new-job')
  await form.getByLabel('Customer', { exact: true }).fill('Test customer')
  await form.getByLabel('Phone', { exact: true }).fill('3175550100')
  await form.getByLabel('Address', { exact: true }).fill('Test address')
  await form.getByLabel('Appliance', { exact: true }).fill('Washer')
  await form.getByLabel('Date', { exact: true }).fill('2026-10-10')
  let attempted: Record<string, unknown> | undefined
  await page.route('**/api/jobs', async route => {
    if (route.request().method() !== 'POST') return route.fulfill({ json: [] })
    attempted = route.request().postDataJSON()
    await route.fulfill({ status: 409, json: { error: 'This appointment time is already booked.' } })
  })
  await form.getByRole('button', { name: 'Save job', exact: true }).click()
  await expect(page.getByText('Unable to create order', { exact: true })).toBeVisible()
  expect(JSON.stringify(attempted)).toContain('12:00 PM - 1:00 PM')
  await expect(form).toBeVisible()
  await expect(form.getByLabel('Customer', { exact: true })).toHaveValue('Test customer')
  await expect(form.getByRole('button', { name: 'Save job', exact: true })).toBeEnabled()
  expect(errors).toEqual([])
})
